import type { Charger } from '../../integrations/ev/openchargemap.client.js';

/**
 * Sample chargers, used only when OCM_API_KEY is unset (Open Charge Map 403s
 * without a key). Deliberately includes sites with NO published price, because
 * that is the common real-world case and the UI must handle it — a mock where
 * everything is neatly priced would hide the very thing that makes EV pricing
 * hard.
 *
 * Always surfaced to the app as source:'mock' so these are never mistaken for
 * real prices.
 */
export const EV_SAMPLE_CHARGERS: Charger[] = [
  {
    id: 'EV-SAMPLE-0001',
    title: 'Southbank Car Park',
    operator: 'InstaVolt',
    address: 'Belvedere Road, London',
    postcode: 'SE1 9PX',
    latitude: 51.5045,
    longitude: -0.1146,
    maxPowerKw: 125,
    connectorTypes: ['CCS (Type 2)', 'CHAdeMO'],
    points: 4,
    pricePencePerKwh: 79,
    usageCostText: '£0.79/kWh',
    status: 'Operational',
    isOperational: true,
    isFree: false,
  },
  {
    id: 'EV-SAMPLE-0002',
    title: 'Holborn Station Car Park',
    operator: 'Pod Point',
    address: 'High Holborn, London',
    postcode: 'WC1V 6NX',
    latitude: 51.5174,
    longitude: -0.1187,
    maxPowerKw: 22,
    connectorTypes: ['Type 2 (Socket Only)'],
    points: 2,
    pricePencePerKwh: 55,
    usageCostText: '55p per kWh',
    status: 'Operational',
    isOperational: true,
    isFree: false,
  },
  {
    id: 'EV-SAMPLE-0003',
    title: 'Waterloo Retail Park',
    operator: 'Gridserve',
    address: 'Waterloo Road, London',
    postcode: 'SE1 8TY',
    latitude: 51.5031,
    longitude: -0.1132,
    maxPowerKw: 350,
    connectorTypes: ['CCS (Type 2)'],
    points: 6,
    // The common real case: OCM has the site but no usable price.
    pricePencePerKwh: null,
    usageCostText: 'Contact operator for tariff',
    status: 'Operational',
    isOperational: true,
    isFree: false,
  },
  {
    id: 'EV-SAMPLE-0004',
    title: 'Tesco Kensington',
    operator: 'Tesco / Pod Point',
    address: "West Cromwell Road, London",
    postcode: 'W14 8PB',
    latitude: 51.4907,
    longitude: -0.2044,
    maxPowerKw: 7,
    connectorTypes: ['Type 2 (Socket Only)'],
    points: 8,
    pricePencePerKwh: 0,
    usageCostText: 'Free (7kW bays), parking limits apply',
    status: 'Operational',
    isOperational: true,
    isFree: true,
  },
  {
    id: 'EV-SAMPLE-0005',
    title: 'Camden Lock',
    operator: 'Osprey',
    address: 'Chalk Farm Road, London',
    postcode: 'NW1 8AH',
    latitude: 51.5414,
    longitude: -0.1461,
    maxPowerKw: 150,
    connectorTypes: ['CCS (Type 2)', 'CHAdeMO'],
    points: 4,
    pricePencePerKwh: 89,
    usageCostText: '£0.89/kWh',
    status: 'Operational',
    isOperational: true,
    isFree: false,
  },
  {
    id: 'EV-SAMPLE-0006',
    title: 'Greenwich Peninsula',
    operator: 'BP Pulse',
    address: 'Millennium Way, London',
    postcode: 'SE10 0PH',
    latitude: 51.4996,
    longitude: 0.0043,
    maxPowerKw: 150,
    connectorTypes: ['CCS (Type 2)'],
    points: 8,
    pricePencePerKwh: 85,
    usageCostText: '85p/kWh (79p for subscribers)',
    status: 'Operational',
    isOperational: true,
    isFree: false,
  },
];
